Feature/chat
danielDeVita/solvd.laba.aliasProject pull request #16
Opened 2023-11-23 21:21 UTC by ArtemAng

I've made a view for rooms and I've also bound Socket's joinRoom to rooms in database. 
If you want to test it, you can use the same route ( /chat/ ), but you alse need to change your token in the file views/room.html.

2023-11-23 21:36 UTC, danielDeVita approved these changes

2023-11-23 23:09 UTC, jszychowskilaba requested changes

2023-11-23 23:09 UTC, jszychowskilaba commented on src/views/chat/all-rooms.html
> +        console.error('Произошла ошибка:', error.message);
I think it would be better if errors are thrown in english

2023-11-24 12:19 UTC, suprugafad commented on src/views/chat/all-rooms.html
> +        console.error('Произошла ошибка:', error.message);
@ArtemAng please translate all in eng

2023-11-25 14:38 UTC, suprugafad approved these changes

2023-11-26 03:48 UTC, jszychowskilaba commented
@ArtemAng there is a pending review in order to make the merge

2023-11-26 10:46 UTC, suprugafad commented
> @ArtemAng there is a pending review in order to make the merge

you requested changes so merging is blocked

2023-11-26 11:13 UTC, jszychowskilaba approved these changes

2023-11-26 11:13 UTC, merged