fix: conflict between ports
danielDeVita/solvd.laba.aliasProject pull request #24
Opened 2023-11-27 13:16 UTC by jszychowskilaba

Fixed a port conflict where chat feature was not correctly attached to the http server, causing a port conflict between express server and socket server

2023-11-27 14:18 UTC, suprugafad approved these changes

2023-11-27 15:18 UTC, danielDeVita requested changes
may be a good idea to update the .envExample file too, (and also add the chat port variable to it, I forgot about that one)

2023-11-27 16:50 UTC, jszychowskilaba commented
> may be a good idea to update the .envExample file too, (and also add the chat port variable to it, I forgot about that one)

Good observation ! I added the port to .envExample. It is not neccesary to add a port to the chat, as it is using the same http server that uses express

2023-11-27 18:30 UTC, ArtemAng approved these changes

2023-11-28 11:10 UTC, FrancescaPavan approved these changes

2023-11-28 11:12 UTC, danielDeVita approved these changes

2023-11-28 11:13 UTC, merged